apiVersion: apps/v1
kind: Deployment
metadata: 
  name: kubedemoapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubedemoapp
  template:
    metadata:
      labels:
        app: kubedemoapp
    spec:
      containers:
      - name: kubedemoapp-container
        image: sabavathlakshmi/kubedemoapp:latest
        ports:
        - containerPort: 80
