apiVersion: apps/v1
kind: Deployment  
metadata:
  name: Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubedemoapp
  template:
    metadata:
      labels:
        app: kubedemoapp
    spec:
      containers:
      - name: kubedemoapp-container
        image: kubedemoapp-image:latest
        ports:
        - containerPort: 80 